#!/usr/bin/env bash

if ! command -v brew &> /dev/null
then
    read -p "Install homebrew? [Y/n] " install_homebrew
    install_homebrew=${install_homebrew:-y}

    if [[ $install_homebrew == [yY] ]]; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
fi

if command -v brew &> /dev/null
then
    brew bundle
fi

# Start with the simple dotfiles
dotfiles=( .bashrc .bash_aliases .bash_colors .bash_profile .bash_prompt .gemrc .vim .vimrc .inputrc .gitconfig .psqlrc )
for i in "${dotfiles[@]}"
do
    if [ ! -e ~/$i ]; then 
        echo "Creating ~/$i -> $(pwd)/$i"
        ln -s $(pwd)/$i $HOME/$i
    else
        echo "~/$i already exists; skipping."
    fi
done

# Create an env-specific file, just in case
if [ ! -f ~/.bashrc_local ]; then
  echo "Creating env-specific .bashrc file."
  echo "# Put environment-specific stuff here." > ~/.bashrc_local
fi

source ~/.bashrc
