#!/usr/bin/env bash

# Install the git submodule so I have my vim plugins
git submodule update --init --recursive

# Start with the simple dotfiles
dotfiles=( .bashrc .bash_aliases .hgrc .vim/ .vimrc .todo.cfg )
for i in "${dotfiles[@]}"
do
    if [ ! -e ~/$i ]; then 
        echo "Creating ~/$i -> $(pwd)/$i"
        ln -s $(pwd)/$i ~/$i
    fi
done

# Create an env-specific file, just in case
if [ ! -f ~/.bashrc.local ]; then
  echo "# Put environment-specific stuff here." > ~/.bashrc.local
fi

# Make special case for .gitconfig to keep GitHub token from getting checked in
cp .gitconfig ~/.gitconfig

# Remind myself to fill in ~/.gitconfig, because I will forget
printf "Don't forget to modify ~/.gitconfig.\n"

